import json

def create_chinese_dict():
    '''
    创造汉语字典并保存
    :return:
    '''
    hero_dict_chinese = dict()
    for key in hero_dict.keys():
        if is_chinese(key) and hero_dict[key] not in hero_dict_chinese:
            hero_dict_chinese[hero_dict[key]] = key

    with open('hero_dict_chinese.json', 'w') as f:
        json.dump(hero_dict_chinese, f)  # 储存字典数据

with open('hero_dict_chinese.json', 'r') as file:
    hero_dict_chinese = json.load(file) # 读取字典数据


# 建立位置名称字典
position_dict = dict()
position_dict['上'] = 'top'
position_dict['上单'] = 'top'
position_dict['上路'] = 'top'
position_dict['top'] = 'top'
position_dict['野'] = 'jungle'
position_dict['打野'] = 'jungle'
position_dict['jungle'] = 'jungle'
position_dict['jug'] = 'jungle'
position_dict['中'] = 'mid'
position_dict['中单'] = 'mid'
position_dict['中路'] = 'mid'
position_dict['mid'] = 'mid'
position_dict['下'] = 'adc'
position_dict['下路'] = 'adc'
position_dict['adc'] = 'adc'
position_dict['ad'] = 'adc'
position_dict['辅'] = 'support'
position_dict['辅助'] = 'support'
position_dict['sup'] = 'support'
position_dict['support'] = 'support'


# 建立英雄名称字典
hero_dict = dict()
hero_dict['万花通灵'] = 'neeko'
hero_dict['妮寇'] = 'neeko'
hero_dict['neeko'] = 'neeko'

hero_dict['不屈之枪'] = 'pantheon'
hero_dict['潘森'] = 'pantheon'
hero_dict['pantheon'] = 'pantheon'

hero_dict['不灭狂雷'] = 'volibear'
hero_dict['狗熊'] = 'volibear'
hero_dict['雷霆嘎巴'] = 'volibear'
hero_dict['volibear'] = 'volibear'

hero_dict['katarina'] = 'katarina'
hero_dict['卡特琳娜'] = 'katarina'
hero_dict['不祥之刃'] = 'katarina'
hero_dict['卡特'] = 'katarina'

hero_dict['ahri'] = 'ahri'
hero_dict['九尾妖狐'] = 'ahri'
hero_dict['阿狸'] = 'ahri'

hero_dict['sion'] = 'sion'
hero_dict['塞恩'] = 'sion'
hero_dict['赛恩'] = 'sion'
hero_dict['亡灵战神'] = 'sion'
hero_dict['老司机'] = 'sion'

hero_dict['lulu'] = 'lulu'
hero_dict['仙灵女巫'] = 'lulu'
hero_dict['露露'] = 'lulu'
hero_dict['璐璐'] = 'lulu'

hero_dict['soraka'] = 'soraka'
hero_dict['索拉卡'] = 'soraka'
hero_dict['众星之子'] = 'soraka'
hero_dict['奶妈'] = 'soraka'
hero_dict['星妈'] = 'soraka'

hero_dict['rengar'] = 'rengar'
hero_dict['傲之追猎者'] = 'rengar'
hero_dict['雷恩加尔'] = 'rengar'
hero_dict['狮子狗'] = 'rengar'
hero_dict['跳跳虎'] = 'rengar'
hero_dict['狮子'] = 'rengar'

hero_dict['qiyana'] = 'qiyana'
hero_dict['琪亚娜'] = 'qiyana'
hero_dict['奇亚娜'] = 'qiyana'
hero_dict['奇娜亚'] = 'qiyana'
hero_dict['琪娜亚'] = 'qiyana'
hero_dict['元素女皇'] = 'qiyana'

hero_dict['lux'] = 'lux'
hero_dict['光辉女郎'] = 'lux'
hero_dict['光女'] = 'lux'
hero_dict['拉克丝'] = 'lux'

hero_dict['兽灵行者'] = 'udyr'
hero_dict['乌迪尔'] = 'udyr'
hero_dict['udyr'] = 'udyr'

hero_dict['anivia'] = 'anivia'
hero_dict['冰晶凤凰'] = 'anivia'
hero_dict['艾尼维亚'] = 'anivia'
hero_dict['冰鸟'] = 'anivia'
hero_dict['不死鸟'] = 'anivia'

hero_dict['lissandra'] = 'lissandra'
hero_dict['丽桑卓'] = 'lissandra'
hero_dict['冰霜女巫'] = 'lissandra'
hero_dict['冰女'] = 'lissandra'

hero_dict['泰隆'] = 'talon'
hero_dict['泰龙'] = 'talon'
hero_dict['talon'] = 'talon'
hero_dict['刀锋之影'] = 'talon'
hero_dict['男刀'] = 'talon'
hero_dict['男刀锋'] = 'talon'

hero_dict['irelia'] = 'irelia'
hero_dict['女刀'] = 'irelia'
hero_dict['艾瑞利亚'] = 'irelia'
hero_dict['艾瑞莉娅'] = 'irelia'
hero_dict['刀锋舞者'] = 'irelia'
hero_dict['刀锋意志'] = 'irelia'
hero_dict['女刀锋'] = 'irelia'
hero_dict['刀妹'] = 'irelia'

hero_dict['sejuani'] = 'sejuani'
hero_dict['瑟庄妮'] = 'sejuani'
hero_dict['北地之怒'] = 'sejuani'
hero_dict['凛冬之怒'] = 'sejuani'
hero_dict['猪女'] = 'sejuani'
hero_dict['猪妹'] = 'sejuani'

hero_dict['twistedfate'] = 'twistedfate'
hero_dict['卡牌大师'] = 'twistedfate'
hero_dict['崔斯特'] = 'twistedfate'
hero_dict['卡牌'] = 'twistedfate'

hero_dict['orianna'] = 'orianna'
hero_dict['发条魔灵'] = 'orianna'
hero_dict['奥丽安娜'] = 'orianna'
hero_dict['奥利安娜'] = 'orianna'
hero_dict['发条'] = 'orianna'
hero_dict['奥莉安娜'] = 'orianna'

hero_dict['lillia'] = 'lillia'
hero_dict['莉莉娅'] = 'lillia'
hero_dict['丽丽亚'] = 'lillia'
hero_dict['莉莉亚'] = 'lillia'
hero_dict['含羞蓓蕾'] = 'lillia'

hero_dict['娜美'] = 'nami'
hero_dict['nami'] = 'nami'
hero_dict['唤潮鲛机'] = 'nami'
hero_dict['唤潮鲛姬'] = 'nami'
hero_dict['人鱼'] = 'nami'
hero_dict['美人鱼'] = 'nami'

hero_dict['lucian'] = 'lucian'
hero_dict['圣枪游侠'] = 'lucian'
hero_dict['奥巴马'] = 'lucian'
hero_dict['卢锡安'] = 'lucian'

hero_dict['poppy'] = 'poppy'
hero_dict['波比'] = 'poppy'
hero_dict['圣锤之毅'] = 'poppy'
hero_dict['钢铁大使'] = 'poppy'

hero_dict['morgana'] = 'morgana'
hero_dict['莫干那'] = 'morgana'
hero_dict['莫甘娜'] = 'morgana'
hero_dict['堕落天使'] = 'morgana'

hero_dict['kalista'] = 'kalista'
hero_dict['卡莉斯塔'] = 'kalista'
hero_dict['滑板鞋'] = 'kalista'
hero_dict['复仇之矛'] = 'kalista'

hero_dict['brand'] = 'brand'
hero_dict['火男'] = 'brand'
hero_dict['布兰德'] = 'brand'
hero_dict['复仇焰魂'] = 'brand'

hero_dict['heimerdinger'] = 'heimerdinger'
hero_dict['黑默丁格'] = 'heimerdinger'
hero_dict['大发明家'] = 'heimerdinger'
hero_dict['发明家'] = 'heimerdinger'
hero_dict['小霸王'] = 'heimerdinger'
hero_dict['大头'] = 'heimerdinger'

hero_dict['karma'] = 'karma'
hero_dict['卡尔马'] = 'karma'
hero_dict['卡尔玛'] = 'karma'
hero_dict['扇子妈'] = 'karma'
hero_dict['天启者'] = 'karma'

hero_dict['ashe'] = 'ashe'
hero_dict['寒冰射手'] = 'ashe'
hero_dict['寒冰'] = 'ashe'
hero_dict['艾希'] = 'ashe'
hero_dict['艾西'] = 'ashe'

hero_dict['奥恩'] = 'ornn'
hero_dict['ornn'] = 'ornn'
hero_dict['山羊'] = 'ornn'
hero_dict['山隐之焰'] = 'ornn'
hero_dict['老山羊'] = 'ornn'

hero_dict['taliyah'] = 'taliyah'
hero_dict['岩雀'] = 'taliyah'
hero_dict['塔莉垭'] = 'taliyah'
hero_dict['塔利亚'] = 'taliyah'
hero_dict['塔莉亚'] = 'taliyah'
hero_dict['燕雀'] = 'taliyah'

hero_dict['trundle'] = 'trundle'
hero_dict['巨魔之王'] = 'trundle'
hero_dict['巨魔'] = 'trundle'
hero_dict['特朗德尔'] = 'trundle'

hero_dict['rakan'] = 'rakan'
hero_dict['幻翎'] = 'rakan'
hero_dict['洛'] = 'rakan'

hero_dict['braum'] = 'braum'
hero_dict['弗雷尔卓德之心'] = 'braum'
hero_dict['布隆'] = 'braum'

hero_dict['zed'] = 'zed'
hero_dict['劫'] = 'zed'
hero_dict['影流之主'] = 'zed'
hero_dict['火影劫'] = 'zed'

hero_dict['kayn'] = 'kayn'
hero_dict['凯隐'] = 'kayn'
hero_dict['影流之镰'] = 'kayn'

hero_dict['garen'] = 'garen'
hero_dict['盖伦'] = 'garen'
hero_dict['德玛西亚之力'] = 'garen'
hero_dict['德玛'] = 'garen'
hero_dict['gay伦'] = 'garen'

hero_dict['quinn'] = 'quinn'
hero_dict['鸟人'] = 'quinn'
hero_dict['奎因'] = 'quinn'
hero_dict['德玛西亚之翼'] = 'quinn'

hero_dict['jarvaniv'] = 'jarvaniv'
hero_dict['皇子'] = 'jarvaniv'
hero_dict['嘉文'] = 'jarvaniv'
hero_dict['嘉文四世'] = 'jarvaniv'
hero_dict['德玛西亚皇子'] = 'jarvaniv'
hero_dict['周杰伦'] = 'jarvaniv'
hero_dict['四阿哥'] = 'jarvaniv'

hero_dict['xinzhao'] = 'xinzhao'
hero_dict['zhaoxin'] = 'xinzhao'
hero_dict['赵信'] = 'xinzhao'
hero_dict['信爷'] = 'xinzhao'
hero_dict['德邦总管'] = 'xinzhao'

hero_dict['shaco'] = 'shaco'
hero_dict['萨科'] = 'shaco'
hero_dict['恶魔小丑'] = 'shaco'
hero_dict['小丑'] = 'shaco'

hero_dict['varus'] = 'varus'
hero_dict['维鲁斯'] = 'varus'
hero_dict['韦鲁斯'] = 'varus'
hero_dict['韦屌丝'] = 'varus'
hero_dict['惩戒之箭'] = 'varus'
hero_dict['惩戒之剑'] = 'varus'

hero_dict['jhin'] = 'jhin'
hero_dict['戏命师'] = 'jhin'
hero_dict['烬'] = 'jhin'

hero_dict['hecarim'] = 'hecarim'
hero_dict['赫卡里姆'] = 'hecarim'
hero_dict['战争之影'] = 'hecarim'
hero_dict['人马'] = 'hecarim'
hero_dict['人驴'] = 'hecarim'

hero_dict['sivir'] = 'sivir'
hero_dict['西维尔'] = 'sivir'
hero_dict['希维尔'] = 'sivir'
hero_dict['战争女神'] = 'sivir'
hero_dict['轮子妈'] = 'sivir'

hero_dict['maokai'] = 'maokai'
hero_dict['茂凯'] = 'maokai'
hero_dict['扭曲树精'] = 'maokai'
hero_dict['大树'] = 'maokai'
hero_dict['树精'] = 'maokai'

hero_dict['rammus'] = 'rammus'
hero_dict['披甲龙龟'] = 'rammus'
hero_dict['拉莫斯'] = 'rammus'
hero_dict['乌龟'] = 'rammus'
hero_dict['龙龟'] = 'rammus'
hero_dict['王八'] = 'rammus'

hero_dict['ezreal'] = 'ezreal'
hero_dict['伊泽瑞尔'] = 'ezreal'
hero_dict['探险家'] = 'ezreal'
hero_dict['拳头儿子'] = 'ezreal'
hero_dict['伊泽诱饵'] = 'ezreal'
hero_dict['小黄毛'] = 'ezreal'
hero_dict['黄毛'] = 'ezreal'
hero_dict['EZ'] = 'ezreal'
hero_dict['ez'] = 'ezreal'

hero_dict['riven'] = 'riven'
hero_dict['瑞文'] = 'riven'
hero_dict['锐雯'] = 'riven'
hero_dict['瑞雯'] = 'riven'
hero_dict['放逐之刃'] = 'riven'

hero_dict['fiora'] = 'fiora'
hero_dict['fiona'] = 'fiora'
hero_dict['无双剑姬'] = 'fiora'
hero_dict['剑姬'] = 'fiora'
hero_dict['菲奥娜'] = 'fiora'

hero_dict['masteryi'] = 'masteryi'
hero_dict['易大师'] = 'masteryi'
hero_dict['易'] = 'masteryi'
hero_dict['无极剑圣'] = 'masteryi'
hero_dict['剑圣'] = 'masteryi'

hero_dict['urgot'] = 'urgot'
hero_dict['厄加特'] = 'urgot'
hero_dict['无畏战车'] = 'urgot'
hero_dict['螃蟹'] = 'urgot'

hero_dict['zilean'] = 'zilean'
hero_dict['基兰'] = 'zilean'
hero_dict['时光守护者'] = 'zilean'
hero_dict['时光'] = 'zilean'
hero_dict['时光老人'] = 'zilean'
hero_dict['时光老头'] = 'zilean'

hero_dict['ekko'] = 'ekko'
hero_dict['艾克'] = 'ekko'
hero_dict['时间刺客'] = 'ekko'

hero_dict['bard'] = 'bard'
hero_dict['巴德'] = 'bard'
hero_dict['星界游神'] = 'bard'

hero_dict['vayne'] = 'vayne'
hero_dict['薇恩'] = 'vayne'
hero_dict['韦恩'] = 'vayne'
hero_dict['维恩'] = 'vayne'
hero_dict['VN'] = 'vayne'
hero_dict['vn'] = 'vayne'
hero_dict['暗夜猎手'] = 'vayne'
hero_dict['伍兹'] = 'vayne'

hero_dict['aatrox'] = 'aatrox'
hero_dict['亚托克斯'] = 'aatrox'
hero_dict['暗裔剑魔'] = 'aatrox'
hero_dict['剑魔'] = 'aatrox'

hero_dict['syndra'] = 'syndra'
hero_dict['球女'] = 'syndra'
hero_dict['辛德拉'] = 'syndra'
hero_dict['辛得拉'] = 'syndra'
hero_dict['暗黑元首'] = 'syndra'
hero_dict['黑暗元首'] = 'syndra'

hero_dict['shen'] = 'shen'
hero_dict['慎'] = 'shen'
hero_dict['暮光之眼'] = 'shen'
hero_dict['肾'] = 'shen'
hero_dict['腰子'] = 'shen'

hero_dict['zoe'] = 'zoe'
hero_dict['佐伊'] = 'zoe'
hero_dict['暮光星灵'] = 'zoe'

hero_dict['kled'] = 'kled'
hero_dict['克列'] = 'kled'
hero_dict['克烈'] = 'kled'
hero_dict['暴怒骑士'] = 'kled'

hero_dict['jinx'] = 'jinx'
hero_dict['暴走萝莉'] = 'jinx'
hero_dict['金克斯'] = 'jinx'
hero_dict['金克丝'] = 'jinx'
hero_dict['萝莉'] = 'jinx'

hero_dict['leona'] = 'leona'
hero_dict['女坦'] = 'leona'
hero_dict['日女'] = 'leona'
hero_dict['雷欧娜'] = 'leona'
hero_dict['蕾欧娜'] = 'leona'
hero_dict['曙光女神'] = 'leona'

hero_dict['jayce'] = 'jayce'
hero_dict['杰斯'] = 'jayce'
hero_dict['杰丝'] = 'jayce'
hero_dict['未来守护者'] = 'jayce'

hero_dict['viktor'] = 'viktor'
hero_dict['维克托'] = 'viktor'
hero_dict['机械先驱'] = 'viktor'
hero_dict['三只手'] = 'viktor'

hero_dict['rumble'] = 'rumble'
hero_dict['兰博'] = 'rumble'
hero_dict['机械公敌'] = 'rumble'

hero_dict['kayle'] = 'kayle'
hero_dict['凯尔'] = 'kayle'
hero_dict['正义天使'] = 'kayle'
hero_dict['天使'] = 'kayle'

hero_dict['galio'] = 'galio'
hero_dict['加里奥'] = 'galio'
hero_dict['正义巨像'] = 'galio'

hero_dict['jax'] = 'jax'
hero_dict['贾克斯'] = 'jax'
hero_dict['贾科斯'] = 'jax'
hero_dict['武器大师'] = 'jax'
hero_dict['武器'] = 'jax'

hero_dict['karthus'] = 'karthus'
hero_dict['卡尔萨斯'] = 'karthus'
hero_dict['卡尔'] = 'karthus'
hero_dict['死亡歌颂者'] = 'karthus'
hero_dict['死亡颂唱者'] = 'karthus'
hero_dict['死歌'] = 'karthus'

hero_dict['amumu'] = 'amumu'
hero_dict['阿木木'] = 'amumu'
hero_dict['木乃伊'] = 'amumu'
hero_dict['木木'] = 'amumu'
hero_dict['殇之木乃伊'] = 'amumu'

hero_dict['aphelios'] = 'aphelios'
hero_dict['厄佩琉斯'] = 'aphelios'
hero_dict['厄斐琉斯'] = 'aphelios'
hero_dict['残月之肃'] = 'aphelios'

hero_dict['skarner'] = 'skarner'
hero_dict['斯卡纳'] = 'skarner'
hero_dict['水晶先锋'] = 'skarner'
hero_dict['蝎子'] = 'skarner'

hero_dict['nocturne'] = 'nocturne'
hero_dict['noc'] = 'nocturne'
hero_dict['NOC'] = 'nocturne'
hero_dict['永恒梦魇'] = 'nocturne'
hero_dict['梦魇'] = 'nocturne'
hero_dict['魔腾'] = 'nocturne'

hero_dict['kindred'] = 'kindred'
hero_dict['永猎双子'] = 'kindred'
hero_dict['千珏'] = 'kindred'

hero_dict['nasus'] = 'nasus'
hero_dict['内瑟斯'] = 'nasus'
hero_dict['狗头'] = 'nasus'
hero_dict['狗头人'] = 'nasus'
hero_dict['沙漠死神'] = 'nasus'

hero_dict['azir'] = 'azir'
hero_dict['黄鸡'] = 'azir'
hero_dict['黄金脆皮鸡'] = 'azir'
hero_dict['阿兹尔'] = 'azir'
hero_dict['沙皇'] = 'azir'
hero_dict['沙漠皇帝'] = 'azir'

hero_dict['tahmkench'] = 'tahmkench'
hero_dict['蛤蟆'] = 'tahmkench'
hero_dict['塔姆'] = 'tahmkench'
hero_dict['河流之王'] = 'tahmkench'

hero_dict['graves'] = 'graves'
hero_dict['格雷福斯'] = 'graves'
hero_dict['格雷弗斯'] = 'graves'
hero_dict['格雷夫斯'] = 'graves'
hero_dict['男枪'] = 'graves'
hero_dict['法外狂徒'] = 'graves'

hero_dict['illaoi'] = 'illaoi'
hero_dict['俄洛依'] = 'illaoi'
hero_dict['俄洛伊'] = 'illaoi'
hero_dict['触手'] = 'illaoi'
hero_dict['触手妈'] = 'illaoi'
hero_dict['触手怪'] = 'illaoi'
hero_dict['海兽祭祀'] = 'illaoi'
hero_dict['海兽祭司'] = 'illaoi'

hero_dict['gangplank'] = 'gangplank'
hero_dict['普朗克'] = 'gangplank'
hero_dict['船长'] = 'gangplank'
hero_dict['海洋之灾'] = 'gangplank'

hero_dict['senna'] = 'senna'
hero_dict['塞纳'] = 'senna'
hero_dict['赛纳'] = 'senna'
hero_dict['赛娜'] = 'senna'
hero_dict['涤魂圣枪'] = 'senna'

hero_dict['nautilus'] = 'nautilus'
hero_dict['泰坦'] = 'nautilus'
hero_dict['深海泰坦'] = 'nautilus'
hero_dict['诺提勒斯'] = 'nautilus'

hero_dict['克格莫'] = 'kogmaw'
hero_dict['kogmaw'] = 'kogmaw'
hero_dict['大嘴'] = 'kogmaw'
hero_dict['深渊巨口'] = 'kogmaw'
hero_dict['克格\'莫'] = 'kogmaw'

hero_dict['fizz'] = 'fizz'
hero_dict['潮汐海灵'] = 'fizz'
hero_dict['小鱼人'] = 'fizz'
hero_dict['鱼人'] = 'fizz'
hero_dict['菲兹'] = 'fizz'

hero_dict['singed'] = 'singed'
hero_dict['辛吉德'] = 'singed'
hero_dict['炼金术士'] = 'singed'
hero_dict['炼金术师'] = 'singed'
hero_dict['炼金'] = 'singed'

hero_dict['malphat'] = 'malphite'
hero_dict['莫菲特'] = 'malphite'
hero_dict['墨菲特'] = 'malphite'
hero_dict['石头人'] = 'malphite'
hero_dict['石头'] = 'malphite'
hero_dict['熔岩巨兽'] = 'malphite'
hero_dict['混分巨兽'] = 'malphite'

hero_dict['ziggs'] = 'ziggs'
hero_dict['吉格斯'] = 'ziggs'
hero_dict['炸弹人'] = 'ziggs'
hero_dict['爆破鬼才'] = 'ziggs'

hero_dict['alistar'] = 'alistar'
hero_dict['牛头酋长'] = 'alistar'
hero_dict['牛头'] = 'alistar'
hero_dict['阿利斯塔'] = 'alistar'
hero_dict['老牛'] = 'alistar'
hero_dict['牛哥'] = 'alistar'

hero_dict['yorick'] = 'yorick'
hero_dict['掘墓'] = 'yorick'
hero_dict['牧魂人'] = 'yorick'
hero_dict['约里克'] = 'yorick'
hero_dict['挑粪工'] = 'yorick'
hero_dict['盗墓男'] = 'yorick'

hero_dict['奥拉夫'] = 'olaf'
hero_dict['奥拉弗'] = 'olaf'
hero_dict['狂战士'] = 'olaf'
hero_dict['狂战'] = 'olaf'

hero_dict['kennen'] = 'kennen'
hero_dict['电耗子'] = 'kennen'
hero_dict['凯南'] = 'kennen'
hero_dict['狂暴之心'] = 'kennen'
hero_dict['天雷'] = 'kennen'

hero_dict['nidalee'] = 'nidalee'
hero_dict['奶大力'] = 'nidalee'
hero_dict['奈德丽'] = 'nidalee'
hero_dict['奶大丽'] = 'nidalee'
hero_dict['豹女'] = 'nidalee'
hero_dict['狂野女猎手'] = 'nidalee'

hero_dict['vladimir'] = 'vladimir'
hero_dict['弗拉基米尔'] = 'vladimir'
hero_dict['猩红收割者'] = 'vladimir'
hero_dict['吸血鬼'] = 'vladimir'

hero_dict['sona'] = 'sona'
hero_dict['娑娜'] = 'sona'
hero_dict['琴女'] = 'sona'
hero_dict['琴瑟仙女'] = 'sona'

hero_dict['taric'] = 'taric'
hero_dict['宝石'] = 'taric'
hero_dict['宝石骑士'] = 'taric'
hero_dict['瓦罗兰之盾'] = 'taric'
hero_dict['瓦洛兰之盾'] = 'taric'
hero_dict['塔里克'] = 'taric'

hero_dict['zac'] = 'zac'
hero_dict['扎克'] = 'zac'
hero_dict['生化魔人'] = 'zac'
hero_dict['橡皮人'] = 'zac'
hero_dict['泥巴人'] = 'zac'
hero_dict['魔人布欧'] = 'zac'

hero_dict['yasuo'] = 'yasuo'
hero_dict['压缩'] = 'yasuo'
hero_dict['亚索'] = 'yasuo'
hero_dict['压索'] = 'yasuo'
hero_dict['风男'] = 'yasuo'
hero_dict['快乐风男'] = 'yasuo'
hero_dict['疾风剑豪'] = 'yasuo'

hero_dict['evelynn'] = 'evelynn'
hero_dict['寡妇'] = 'evelynn'
hero_dict['寡妇制造者'] = 'evelynn'
hero_dict['痛苦之拥'] = 'evelynn'
hero_dict['伊芙琳'] = 'evelynn'

hero_dict['twitch'] = 'twitch'
hero_dict['瘟疫之源'] = 'twitch'
hero_dict['老鼠'] = 'twitch'
hero_dict['耗子'] = 'twitch'
hero_dict['图奇'] = 'twitch'

hero_dict['diana'] = 'diana'
hero_dict['皎月'] = 'diana'
hero_dict['皎月女神'] = 'diana'
hero_dict['黛安娜'] = 'diana'

hero_dict['caitlyn'] = 'caitlyn'
hero_dict['皮城女警'] = 'caitlyn'
hero_dict['女警'] = 'caitlyn'
hero_dict['凯特琳'] = 'caitlyn'

hero_dict['vi'] = 'vi'
hero_dict['皮城执法官'] = 'vi'
hero_dict['蔚'] = 'vi'

hero_dict['leesin'] = 'leesin'
hero_dict['瞎子'] = 'leesin'
hero_dict['盲僧'] = 'leesin'
hero_dict['李青'] = 'leesin'

hero_dict['warwick'] = 'warwick'
hero_dict['狼人'] = 'warwick'
hero_dict['狼爪'] = 'warwick'
hero_dict['沃里克'] = 'warwick'
hero_dict['祖安怒兽'] = 'warwick'

hero_dict['drmundo'] = 'drmundo'
hero_dict['祖安狂人'] = 'drmundo'
hero_dict['蒙多'] = 'drmundo'
hero_dict['蒙多医生'] = 'drmundo'

hero_dict['阿卡丽'] = 'akali'
hero_dict['akali'] = 'akali'
hero_dict['离群之刺'] = 'akali'
hero_dict['暗影之拳'] = 'akali'

hero_dict['ryze'] = 'ryze'
hero_dict['瑞兹'] = 'ryze'
hero_dict['流浪法师'] = 'ryze'
hero_dict['浪法'] = 'ryze'
hero_dict['流浪'] = 'ryze'
hero_dict['符文法师'] = 'ryze'

hero_dict['ivern'] = 'ivern'
hero_dict['翠神'] = 'ivern'
hero_dict['小菊'] = 'ivern'
hero_dict['蔡徐坤'] = 'ivern'
hero_dict['艾翁'] = 'ivern'

hero_dict['瑟提'] = 'sett'
hero_dict['sett'] = 'sett'
hero_dict['万豪'] = 'sett'
hero_dict['腕豪'] = 'sett'

hero_dict['corki'] = 'corki'
hero_dict['飞机'] = 'corki'
hero_dict['英勇投弹手'] = 'corki'
hero_dict['库奇'] = 'corki'

hero_dict['zyra'] = 'zyra'
hero_dict['荆棘之兴'] = 'zyra'
hero_dict['婕拉'] = 'zyra'

hero_dict['renekton'] = 'renekton'
hero_dict['雷克顿'] = 'renekton'
hero_dict['鳄鱼'] = 'renekton'
hero_dict['大鳄鱼'] = 'renekton'
hero_dict['荒漠屠夫'] = 'renekton'

hero_dict['draven'] = 'draven'
hero_dict['德莱文'] = 'draven'
hero_dict['荣耀行刑官'] = 'draven'
hero_dict['文森特'] = 'draven'

hero_dict['blitzcrank'] = 'blitzcrank'
hero_dict['机器人'] = 'blitzcrank'
hero_dict['蒸汽机器人'] = 'blitzcrank'
hero_dict['布里茨'] = 'blitzcrank'

hero_dict['kaisa'] = 'kaisa'
hero_dict['卡沙'] = 'kaisa'
hero_dict['卡莎'] = 'kaisa'
hero_dict['虚空之女'] = 'kaisa'

hero_dict['velkoz'] = 'velkoz'
hero_dict['大眼'] = 'velkoz'
hero_dict['大眼怪'] = 'velkoz'
hero_dict['虚空之眼'] = 'velkoz'
hero_dict['维克兹'] = 'velkoz'

hero_dict['malzahar'] = 'malzahar'
hero_dict['蚂蚱'] = 'malzahar'
hero_dict['马儿扎哈'] = 'malzahar'
hero_dict['马尔扎哈'] = 'malzahar'
hero_dict['虚空先知'] = 'malzahar'

hero_dict['chogath'] = 'chogath'
hero_dict['虚空恐惧'] = 'chogath'
hero_dict['大虫子'] = 'chogath'
hero_dict['科加斯'] = 'chogath'

hero_dict['khazix'] = 'khazix'
hero_dict['螳螂'] = 'khazix'
hero_dict['卡兹克'] = 'khazix'
hero_dict['虚空掠夺者'] = 'khazix'

hero_dict['kassadin'] = 'kassadin'
hero_dict['卡萨丁'] = 'kassadin'
hero_dict['虚空行者'] = 'kassadin'

hero_dict['reksai'] = 'reksai'
hero_dict['雷克塞'] = 'reksai'
hero_dict['虚空遁地兽'] = 'reksai'
hero_dict['挖掘机'] = 'reksai'

hero_dict['tryndamere'] = 'tryndamere'
hero_dict['蛮王'] = 'tryndamere'
hero_dict['蛮子'] = 'tryndamere'
hero_dict['蛮族之王'] = 'tryndamere'
hero_dict['泰达米尔'] = 'tryndamere'

hero_dict['elise'] = 'elise'
hero_dict['蜘蛛'] = 'elise'
hero_dict['蜘蛛女皇'] = 'elise'
hero_dict['伊利斯'] = 'elise'
hero_dict['伊莉丝'] = 'elise'

hero_dict['pyke'] = 'pyke'
hero_dict['派克'] = 'pyke'
hero_dict['血港鬼影'] = 'pyke'

hero_dict['sylas'] = 'sylas'
hero_dict['解脱者'] = 'sylas'
hero_dict['塞拉斯'] = 'sylas'
hero_dict['赛拉斯'] = 'sylas'
hero_dict['偷男'] = 'sylas'

hero_dict['leblanc'] = 'leblanc'
hero_dict['乐芙兰'] = 'leblanc'
hero_dict['妖姬'] = 'leblanc'
hero_dict['诡术妖姬'] = 'leblanc'

hero_dict['darius'] = 'darius'
hero_dict['诺手'] = 'darius'
hero_dict['诺克萨斯之手'] = 'darius'
hero_dict['小学生之手'] = 'darius'
hero_dict['德莱厄斯'] = 'darius'

hero_dict['swain'] = 'swain'
hero_dict['斯维因'] = 'swain'
hero_dict['乌鸦'] = 'swain'
hero_dict['诺克萨斯统领'] = 'swain'
hero_dict['策士统领'] = 'swain'

hero_dict['missfortune'] = 'missfortune'
hero_dict['赏金'] = 'missfortune'
hero_dict['赏金猎人'] = 'missfortune'
hero_dict['厄运小姐'] = 'missfortune'
hero_dict['女枪'] = 'missfortune'

hero_dict['teemo'] = 'teemo'
hero_dict['提莫'] = 'teemo'
hero_dict['提百万'] = 'teemo'
hero_dict['迅捷斥候'] = 'teemo'

hero_dict['xerath'] = 'xerath'
hero_dict['远古巫灵'] = 'xerath'
hero_dict['泽拉斯'] = 'xerath'
hero_dict['王继超'] = 'xerath'
hero_dict['王纪超'] = 'xerath'

hero_dict['fiddlesticks'] = 'fiddlesticks'
hero_dict['稻草人'] = 'fiddlesticks'
hero_dict['远古恐惧'] = 'fiddlesticks'
hero_dict['费德提克'] = 'fiddlesticks'

hero_dict['gnar'] = 'gnar'
hero_dict['纳尔'] = 'gnar'
hero_dict['小纳尔'] = 'gnar'
hero_dict['迷失之牙'] = 'gnar'

hero_dict['xayah'] = 'xayah'
hero_dict['霞'] = 'xayah'
hero_dict['逆羽'] = 'xayah'

hero_dict['veigar'] = 'veigar'
hero_dict['小法'] = 'veigar'
hero_dict['小法师'] = 'veigar'
hero_dict['邪恶小法师'] = 'veigar'
hero_dict['维嘉'] = 'veigar'
hero_dict['维迦'] = 'veigar'

hero_dict['gragas'] = 'gragas'
hero_dict['啤酒人'] = 'gragas'
hero_dict['酒桶'] = 'gragas'
hero_dict['古拉加斯'] = 'gragas'

hero_dict['mordekaiser'] = 'mordekaiser'
hero_dict['铁男'] = 'mordekaiser'
hero_dict['莫德凯撒'] = 'mordekaiser'
hero_dict['莫得感情'] = 'mordekaiser'
hero_dict['铁铠冥魂'] = 'mordekaiser'

hero_dict['aurelionsol'] = 'aurelionsol'
hero_dict['龙王'] = 'aurelionsol'
hero_dict['筑星龙王'] = 'aurelionsol'
hero_dict['铸星龙王'] = 'aurelionsol'
hero_dict['奥瑞利安·索尔'] = 'aurelionsol'
hero_dict['奥瑞利安索尔'] = 'aurelionsol'
hero_dict['索尔'] = 'aurelionsol'
hero_dict['奥瑞利安'] = 'aurelionsol'

hero_dict['nunu'] = 'nunu'
hero_dict['努努'] = 'nunu'
hero_dict['雪人'] = 'nunu'
hero_dict['雪原双子'] = 'nunu'

hero_dict['camelle'] = 'camille'
hero_dict['卡密尔'] = 'camille'
hero_dict['卡蜜尔'] = 'camille'
hero_dict['青钢影'] = 'camille'

hero_dict['janna'] = 'janna'
hero_dict['风女'] = 'janna'
hero_dict['伽娜'] = 'janna'
hero_dict['风暴之怒'] = 'janna'

hero_dict['thresh'] = 'thresh'
hero_dict['锤石'] = 'thresh'
hero_dict['魂锁典狱长'] = 'thresh'

hero_dict['yuumi'] = 'yuumi'
hero_dict['猫咪'] = 'yuumi'
hero_dict['猫'] = 'yuumi'
hero_dict['魔法猫咪'] = 'yuumi'
hero_dict['优米'] = 'yuumi'
hero_dict['悠米'] = 'yuumi'

hero_dict['cassiopeia'] = 'cassiopeia'
hero_dict['蛇女'] = 'cassiopeia'
hero_dict['魔蛇之拥'] = 'cassiopeia'
hero_dict['卡西奥佩娅'] = 'cassiopeia'

hero_dict['tristana'] = 'tristana'
hero_dict['小炮'] = 'tristana'
hero_dict['炮娘'] = 'tristana'
hero_dict['麦林炮手'] = 'tristana'
hero_dict['崔丝塔娜'] = 'tristana'

hero_dict['annie'] = 'annie'
hero_dict['安妮'] = 'annie'
hero_dict['火女'] = 'annie'
hero_dict['黑暗之女'] = 'annie'

hero_dict['monkeyking'] = 'monkeyking'
hero_dict['猴子'] = 'monkeyking'
hero_dict['孙悟空'] = 'monkeyking'
hero_dict['悟空'] = 'monkeyking'
hero_dict['齐天大圣'] = 'monkeyking'

hero_dict['shyvana'] = 'shyvana'
hero_dict['龙女'] = 'shyvana'
hero_dict['小龙女'] = 'shyvana'
hero_dict['龙血舞姬'] = 'shyvana'
hero_dict['龙血武姬'] = 'shyvana'
hero_dict['希瓦娜'] = 'shyvana'

hero_dict['gwen'] = 'gwen'
hero_dict['格温'] = 'gwen'
hero_dict['绫罗娃娃'] = 'gwen'
hero_dict['灵罗娃娃'] = 'gwen'
hero_dict['剪刀妹'] = 'gwen'

hero_dict['akshan'] = 'akshan'
hero_dict['阿克尚'] = 'akshan'
hero_dict['影哨'] = 'akshan'

hero_dict['yone'] = 'yone'
hero_dict['永恩'] = 'yone'
hero_dict['封魔剑魂'] = 'yone'

hero_dict['vex'] = 'vex'
hero_dict['薇古斯'] = 'vex'
hero_dict['薇古丝'] = 'vex'
hero_dict['薇古思'] = 'vex'
hero_dict['愁云使者'] = 'vex'
hero_dict['熬夜波比'] = 'vex'


hero_dict['belveth'] = 'belveth'
hero_dict['卑尔维斯'] ='belveth'
hero_dict['虚空女皇'] ='belveth'

hero_dict['viego'] = 'viego'
hero_dict['弗耶格'] ='viego'
hero_dict['破败之王'] ='viego'
hero_dict['破败王'] ='viego'

hero_dict['samira'] = 'samira'
hero_dict['沙弥啦'] ='samira'
hero_dict['莎弥拉'] ='samira'
hero_dict['沙漠玫瑰'] ='samira'

hero_dict['nilah'] ='nilah'
hero_dict['尼菈'] ='nilah'
hero_dict['妮菈'] ='nilah'
hero_dict['不羁之悦'] ='nilah'

hero_dict['zeri'] ='zeri'
hero_dict['泽丽'] ='zeri'
hero_dict['祖安花火'] ='zeri'

hero_dict['renata'] ='renata'
hero_dict['列娜塔'] ='renata'
hero_dict['炼金男爵'] ='renata'

hero_dict['rell'] ='rell'
hero_dict['芮尔'] ='rell'
hero_dict['镕铁少女'] ='rell'
hero_dict['熔铁少女'] ='rell'

hero_dict['reraphine'] ='seraphine'
hero_dict['萨勒芬妮'] ='seraphine'
hero_dict['星籁歌姬'] ='seraphine'
hero_dict['歌姬'] ='seraphine'
